### ISSUE TITLE
Correct the wiki about Get Clone command

### ISSUE THREAD

**Issue by bortolin** [sqlcollaborative/dbaclone#125]
Hi,

In the wiki page "Get Clone" there is syntax error on command.

Get-DcnCClone instead of Get-DcnClone.

PS: Congratulations on the beautiful project is definitely very very helpful !!!

**Comment by sanderstad** [comment]
Thank you for this. 

I'm very happy that this project helps you out. 
If you have a case how you're using it, and want to share it, let me know because I'm always interested in how people are using it.
