### ISSUE TITLE
Execute script pre-image creation

### ISSUE THREAD

**Issue by bortolin** [sqlcollaborative/dbaclone#126]
It might be interesting to have the ability to run a script before creating an image in the New-DcnImage command.

Something like this:

`New-DcnImage -SourceSqlInstance Server1 -DestinationSqlInstance Server1 -Image
NetworkPath \\ server1 \ images -Database DatabaseName -CreateFullBackup -ExecuteSql ScriptFile.sql`

This is useful if you need to modify some data in database before the image was created. (Masking some data for example)

**Comment by DatAssCode** [comment]
This would also be nice to have for New-DcnClones as we have to enable CLR and set trustworthy every time we create a clone.
