### ISSUE TITLE
Cannot remove clone if paths are missing

### ISSUE THREAD

**Issue by blitzmann** [sqlcollaborative/dbaclone#88]
**Before submitting the bug**
- [x] Ensure you are able to reproduce it on the latest released version (_we release often_)
- [x] Verified this bug is not already reported in an issue
- [x] Verified errors are not related to permissions
- [x] Can reproduce in a clean PowerShell session (_clean = `powershell -NoProfile`_)

**Describe the bug**
I am attempting to remove the Clone using the `Remove-DcnClone` command. The image was deleted (during an attempt to clean up some files during testing), and it's failing with a missing file exception. I understand that best practices dictate that the command is used to remove the clone image, but there may be circumstances where this outside of the normal workflow of using the commands.

**To Reproduce**
```powershell
PS C:\Users\Administrator\Desktop\PSDatabaseClone> Remove-DcnClone -Database SOClone1
Confirm
Are you sure you want to perform this action?
Performing the operation "Testing module setup" on target "Test-DcnConfiguration".
[Y] Yes [A] Yes to All [N] No [L] No to All [S] Suspend [?] Help (default is "Yes"): a
Remove-Item : Cannot find path 'C:\Program Files\Microsoft SQL Server\MSSQL12.DEVSQL\MSSQL\DATA\clone\SOClone1' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\dbaclone\0.10.2\dbaclone.psm1:1728 char:37
+ ...     $null = Remove-Item -Path "$($item.AccessPath)" -Credential $Cred ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\clone\SOClone1:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemComman
```

**Expected behavior**

I should be able to remove the clone regardless of if the image is missing (indeed, if there's a corrupted / missing image, one would probably want to remove the record in the database). Additionally, the command should remove the database from the instance as well (don't knwo if it already does this)

**Environmental data**

 - PowerShell: 
```

Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


```

**Comment by sanderstad** [comment]
that makes sense. that's one of those scenarios you only get when people start using it ;)

I will look into that

**Comment by sanderstad** [comment]
Changed name because it does not apply to the image file, but it applies to the access path and VHD file for the clone
