### ISSUE TITLE
Cannot image database on another server

### ISSUE THREAD

**Issue by blitzmann** [sqlcollaborative/dbaclone#90]
**Describe the bug**
So, I want to state first off that I'm not sure if this is even a thing. I'm not sure if the scripts are designed to create a new image between different servers, or if the intention is to have the host with the database do the imaging.

If its the latter, feel free to close this. But if it's the former, then I cannot get this to work properly.

I have two SQL servers: DEVSQL and PRODSQL. I am attempting to image a database on PROD server (using last full backup), and create the image on DEVSQL's `D:\Images` directory. Essentially, PRODSQL has the database backup file, but otherwise isn't involved (script is run on DEVSQL, and image is saved to DEVSQL)

```
PS C:\Users\Administrator\Desktop\PSDatabaseClone> New-DcnImage -SourceSqlInstance PRODSQL\MSSQLSERVER -DestinationSqlInstance DEVSQL\MSSQLSERVER -ImageNetworkPath \\localhost\D$\Images -DestinationSqlCredential $cred -SourceSqlCredential $cred -Database StackOverflow2010
VERBOSE: [18:47:28][New-DcnImage] Setting vhd type to 'VHDX'
VERBOSE: [18:47:28][Test-DcnConfiguration] Checking configurations
VERBOSE: [18:47:28][Test-DcnConfiguration] Attempting to connect to PSDatabaseClone database server DEVSQL..
VERBOSE: [18:47:29][Test-DcnConfiguration] Finished checking configurations
VERBOSE: [18:47:29][New-DcnImage] Started image creation
VERBOSE: [18:47:29][New-DcnImage] Attempting to connect to Sql Server PRODSQL..
VERBOSE: [18:47:57][New-DcnImage] Converted '\\localhost\D$\Images' to 'D:\Images'
VERBOSE: [18:47:57][New-DcnImage] Creating image for database [StackOverflow2010] from PRODSQL
VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM 
Win32_LogicalDisk WHERE DeviceId='D:','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: [18:47:57][New-DcnImage] Trying to retrieve the last full backup for [StackOverflow2010]
VERBOSE: [18:47:58][Get-DbaDbBackupHistory] Processing StackOverflow2010
VERBOSE: [18:47:58][Get-DbaDbBackupHistory] Executing sql query on [PRODSQL].
VERBOSE: [18:47:58][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [18:47:58][Get-DbaDbBackupHistory] 1 result-groups found.
WARNING: [18:31:49][New-DcnImage] Could not access the full backup file. Check if it exists or that you have 
enough privileges to access it
```

I assume this is because it's getting the backup path, which is `D:\Data\Backup\StackOverflow_<numbers>.bak` on PRODSQL and trying to work with it on DEVSQL, where it doesn't exist.

**Expected behavior**
I would think that I would be able to restore a backup from another server onto the destination instance. If this isn't supported, then would it be possible to display a message stating that image creation using different servers is not supported?

**Comment by sanderstad** [comment]
This would only work if the backup file would be on a share that's accessible for the DEV instance.
That is a security risk and I don't think that's a good way to go.

However, I recently made a change to the New-DcnImage command to allow for you to pass a full backup file. 

![image](https://user-images.githubusercontent.com/6154981/74660354-47d05000-5196-11ea-91ae-0d88e297439e.png)

@blitzmann That would solve this problem. Let me know what you think

**Comment by blitzmann** [comment]
>However, I recently made a change to the New-DcnImage command to allow for you to pass a full backup file.

That was actually going to be my next question - if we already have a backup file, would the be a way to bypass that step altogether and go directly to the file. Excellent!

I'll have to test tho, I'll let you know how this works out. Thanks!

**Comment by sanderstad** [comment]
@blitzmann Check PR #92

**Comment by sanderstad** [comment]
I'm going to close the issue because it has become stale. If this is not solved please re-open the issue.

**Comment by KazgunovAG** [comment]
Hi there. 
I'm trying to use New-DcnImage feature to create clone of database from an existing bak file. Obviously, it is not necessary to provide -SourceSqlInstance parameter in this case, but it is. Therefore, some checks like existence of database on SourceSqlInstance and ImageLocalPath
`           if ((Test-DbaPath -Path $ImageLocalPath -SqlInstance $SourceSqlInstance -SqlCredential $DestinationCredential) -ne $true) {
                Stop-PSFFunction -Message "Image local path $ImageLocalPath is not valid directory or can't be reached." -Target $SourceSqlInstance
                return                
            }`
also becomes unnecessary. 
Am I right or there are some circumstances that force to provide -SourceSqlInstance parameter anyway?
